craigslist_rails/config/routes.rb
CraigslistRails::Application.routes.draw do
get "welcome/index"

root to: 'welcome#index'
resources :categories do
  resources :posts
end
resources :users

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

end

craigslist_rails/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
end

craigslist_rails/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
end

craigslist_rails/app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts

  #has_secure_password

    def self.authenticate(params)
    user = User.find_by_name(params[:name])
    return user if user && (user.password == params[:password])
    nil # either invalid email or wrong password
    end

end

craigslist_rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	#This method is needed in order for current_user to be accessible in the view.
  helper_method :current_user

  def current_user
    @_current_user ||= User.find_by_id(session[:current_user_id]) if session[:current_user_id]
  	# @_current_user ||= session[:current_user_id] && User.find_by_id(session[:current_user_id])
  end

end

craigslist_rails/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
     @categories = Category.all
  end

  def new

  end

  def show
    @category = Category.find(params[:id])
    redirect_to category_posts_path(@category.id)
  end


end

craigslist_rails/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @category = Category.find(params[:category_id])
    @posts = @category.posts
    # redirect_to category_posts_path
  end

  def show
    @category = Category.find(params[:category_id])
    @post = Post.find(params[:id])
  end

  def create
  	@post = current_user.posts.new(title: params[:post][:title], body: params[:post][:body], category_id: params[:post][:category_id])

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
  end

  def destroy
  end



end

craigslist_rails/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # "Create" a login, aka "log the user in"
  def index
  end

  def create
    if user = User.authenticate(params[:session])
      session[:current_user_id] = user.id
      redirect_to categories_path
    else
      @error = "WRONG!"
      render "welcome/index"
      #redirect_to welcome_index_path
    end

  end

  def destroy
    # Remove the user id from the session
    @_current_user = session[:current_user_id] = nil
    redirect_to root_path
  end
end

craigslist_rails/app/controllers/users_controller.rb
class UserController < ApplicationController

def index

end

end

craigslist_rails/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

def index
  render :index
end

end

craigslist_rails/app/helpers/application_helper.rb
module ApplicationHelper
end

craigslist_rails/app/views/categories/index.html.erb
<h1> Welcome </h1>


<% @categories.each do |category| %>
<%= link_to 'Show', category_path(category) %> <%= category.title %> <br>
<% end %>

craigslist_rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CraigslistRails</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

  <nav>
    <ul>
      <li><%= link_to 'Home', root_path %></li>
      <li></li>
    </ul>
  </nav>

<body>

<%= yield %>

</body>
</html>

craigslist_rails/app/views/posts/index.html.erb
<h1> Posts for "<%= @category.title %>" </h1>
<% @posts.each do |eachpost| %>
<%= link_to 'Show me the post', category_post_path(@category.id, eachpost.id) %> <%= eachpost.title %>  <br>
<% end %>


<%= form_for :post, url: category_posts_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

craigslist_rails/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<h3><%= @post.body %></h3>

craigslist_rails/app/views/welcome/index.html.erb
<h1> Welcome to Craiglist Junior </h1>

<h2>To view posts only, <%= link_to "click here to see a list of categories", controller: "categories" %></h2>


<h2>To create a post, you must first login:</h2>

<p><% if @error %></p>
<%= @error %>
<% end %>

<%= link_to "logout", logout_path, method: :delete if current_user%>

<%= form_for(:session, url: login_path) do |f| %>
<p>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label :password %> <br>
  <%= f.text_field :password %>
</p>
  <p>
  <%= f.submit "Sign In" %>
  </p>
<% end %>